- alias: Notify me when sun sets
  trigger:
    platform: sun
    event: sunset
  action:
    service: notify.slack
    data:
      message: "Slunce zaslo"
- alias: Notify me when sun rises
  trigger:
    platform: sun
    event: sunrise
  action:
    service: notify.slack
    data:
      message: "Slunce vyslo"
- alias: TMEP reporting
  trigger:
    platform: time
    minutes: '/5'
    seconds: 0
  action:
    service: notify.TMEP_REST
    data_template:
      message: "{{ float(states.sensor.pokus_teplota.state) }}"
      title: "{{ float(states.sensor.pokus_vlhkost.state) }}"
